
export const LEFTMENU = 'LEFTMENU';
export const LEFTMENU_RESULT = 'LEFTMENU_RESULT';

export const DEFAULTQUERY_SUCCESS = 'DEFAULTQUERY_SUCCESS';
export const DEFAULTQUERY_FAIL = 'DEFAULTQUERY_FAIL';
export const DEFAULTQUERY_RESULT = 'DEFAULTQUERY_RESULT';


export const LOGIN_RESULT = 'LOGIN_RESULT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'